version: '3.8'

services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432"
    volumes:
      # Persist database data in a local folder
      - ./postgres-data:/var/lib/postgresql/data
      # Run initialization script on first startup
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped